2025-03-01T09:56:26.277Z - Backend error: Traceback (most recent call last):
  File "/home/zombie/ailinux/backend/app.py", line 9, in <module>
    from flask import Flask, jsonify, request, send_from_directory
2025-03-01T09:56:26.278Z - Backend error: ModuleNotFoundError: No module named 'flask'
